version: '3.4'

services:
    mb4-web-dev:
        build: 
            context: .
            target: dev-stage
        image: pg-web-dev:1.0
        container_name: pg-web-container-dev
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - "8081:8080"