version: '3.4'

services:
    pg-web-prod:
        build: .
        image: pg-web-prod:1.0
        container_name: pg-web-container-prod
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - "8082:80"